### PR TITLE
Handle keyboard escape, focus on first input on open modal, and contain tab navigation

### LINKED ISSUE #1660: Improve keyboard navigation for modals
Relevant Components:

- All Modals

Description
When focus is on a modal, the “esc” key should exit the modal.

People using the keyboard often use hotkeys such as “esc” to navigate, and when the element does not behave as expected, confusion can occur.

People with vision and cognitive issues often use solely the keyboard to navigate.

An event listener for the “esc” key, resulting in the modal closing, would improve the accessibility of this element.

Solution
Make sure the modal acts as can be reasonably expected by a user - specifically, the “esc” key should exit the modal.

### LINKED ISSUE #1661: Retain focus on modal until closed
Relevant Components:

- All Modals

Description
The login modal on the home page allows focus to continue onto the rest of the page.

This can cause confusion for non-sighted or low vision users because the screen reader will continue to announce the next focused element, and the user is likely unaware that there is a modal open at all.

Employing a keyboard trap while the modal is open, as well as manually setting focus to the modal on its appearance, will make the element more accessible as well as more usable in general.
Solution
Make sure the modal acts as can be reasonably expected by a user - specifically, focus should remain in the modal.

Relates to #1660

### LINKED ISSUE #1692: Login modal keyboard accessibility
Tab focus on background after opening Login modal. To reproduce:

1. Tab to Login on home page
2. Press enter to open Login modal
3. Press Tab

You will notice that the focus remains in background and moves to Register on next Tab press. Focus should move to Login modal.

May relate to #1660

### PR DESCRIPTION
**Pull request by ghost**
# Description

Handle keyboard escape, focus on first input on open modal, and contain tab navigation.

Fixes https://github.com/TexasDigitalLibrary/Vireo/issues/1660, https://github.com/TexasDigitalLibrary/Vireo/issues/1661, and https://github.com/TexasDigitalLibrary/Vireo/issues/1692

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by kaladay — DISMISSED** [review]

**Comment by kaladay** [comment]
The code looks fine but this appears to not be working for some reason in my environment.

**Comment by kaladay** [comment]
I did some testing and it almost works.

If I click anywhere other than the buttons/links in the model with the mouse then the escape key no longer works.

I added some debug statements and the log shows something like this:

This first one is when the escape works as expected.
See how the element is undefined.
See how the Escape handler is triggered.
```
DEBUG: keydown handler code Escape
DEBUG: keydown fired, element undefined , code Escape
```

This second one is when the escape fails to work as expected.
See how There is now an element (fade in) involved in the event.
See how there is no Escape handler debug message.
```
DEBUG: keydown fired, element jQuery.fn.init [div#submissionStatus.modal.fade.in] , code Escape
```

I think what is going on here is that the fade in/out modal code is grabbing the mouse/keyboard as well and messing up the event handler.

This brings up the question of whether or not such a problem is a Vireo problem or a weaver problem.

I created the debug log as follows:
```js
bodyElement.on('keydown', function (event) {
console.log("DEBUG: keydown fired, element", modalElement, ", code", event.code);
    if (modalElement && event.code === 'Tab') {
...
var handleKeydown = function (event) {
console.log("DEBUG: keydown handler code", event.code);
    if (event.code === 'Escape') {
```

**Comment by kaladay** [comment]
I think what is going on is:
1) Click inside modal but not ony any field.
2) The focus is changed to the fade in/out code.

I can click back on any field and escape works.
We may want a mouse click check to see if the click is inside the modal (but not on any field).
If the click is inside the modal but not on any field, then we should make sure the focus is set to the modal so that our escape keyboard event will work as intended.

**Comment by ghost** [comment]
@kaladay thanks for the review. Will read carefully and attempt improving functionality.

**Review by kaladay — APPROVED** [review]
code looks fine and quick tests show that it works as expected.

**Pull request merged**
